listen_host: 127.0.0.1
listen_port: 8080

connect_timeout: 3.0
read_timeout: 15.0
write_timeout: 15.0
total_timeout: 30.0

max_client_conns: 2000
max_conns_per_upstream: 2000

upstreams:
  - host: 127.0.0.1
    port: 9001
  - host: 127.0.0.1
    port: 9002
